file(GLOB_RECURSE _source_list CONFIGURE_DEPENDS "*.c" "*.cpp" "*.h" "*.hpp")

add_library(PixieUI STATIC ${_source_list})

set_target_properties(PixieUI PROPERTIES
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED ON
)

target_include_directories(PixieUI PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../")

target_link_libraries(PixieUI PUBLIC glad)
target_link_libraries(PixieUI PUBLIC glfw)

if (MSVC)
    target_compile_options(PixieUI PRIVATE /W4 /WX)
else()
    target_compile_options(PixieUI PRIVATE -Wall -Werror)
endif()

foreach(_source IN ITEMS ${_source_list})
    get_filename_component(_source_path "${_source}" PATH)
    string(REPLACE "${CMAKE_CURRENT_SOURCE_DIR}" "" _group_path "${_source_path}")
    string(REPLACE "../" "" _group_path "${_group_path}")
    source_group("${_group_path}" FILES "${_source}")
endforeach()
